apiVersion: v1
kind: Service
metadata:
  name: rsvp-gateway
  labels:
    run: rsvp-gateway
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    run: rsvp-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-gateway
spec:
  selector:
    matchLabels:
      run: rsvp-gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: rsvp-gateway
    spec:
      containers:
      - name: rsvp-gateway
        image: phphuc7989/rsvp-gateway:latest
        resources:
          limits:
            cpu: '200m'
            memory: '256Mi'
        env:
          - name: REDIS_CONNECT
            value: redis-master
        ports:
        - containerPort: 4000
        livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
        readinessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
