apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phpppd-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: phpppd-ip
spec:
    rules:
    - http:
        paths:
        - path: /graphql
          backend:
            serviceName: rsvp-gateway
            servicePort: 4000
        - path: /*
          backend:
            serviceName: rsvp-react-client
            servicePort: 80
